server:
  port: 1009

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

cloud:
  client:
    oauth:
      sample-oauth:
        url: http://localhost:1008
        key: oauth1_consumer_key_of_sample_service
        secret: oauth1_consumer_secret_of_sample_service

    signer:
      sample-signer:
        url: cloud.client.sample-signer.url
        app-id: cloud.client.sample-signer.app-id
        app-key: cloud.client.sample-signer.app-key

    sample:
      url: http://localhost:1008